apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    argo-zombies/ignore: "true"
data:
  .argo-zombies.yaml: |
    dashboards:
      github:
        enabled: {{ .Values.config.dashboards.github.enabled }}
        repo: {{ .Values.config.dashboards.github.repo | quote }}

    exclusions:
      namespaces:
        {{- .Values.config.exclusions.namespaces | toYaml | nindent 8 }}
      resources:
        {{- .Values.config.exclusions.resources | toYaml | nindent 8 }}
      selectors:
        {{- .Values.config.exclusions.selectors | toYaml | nindent 8 }}
      gvrs:
        {{- .Values.config.exclusions.gvrs | toYaml | nindent 8 }}
      bundles:
        {{- .Values.config.exclusions.bundles | toYaml | nindent 8 }}
