apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    henrywhitaker3.github.com/argo-zombies: "ignore"
data:
  .argo-zombies.yaml: |
    exclusions:
      namespaces:
        {{- .Values.config.exclusions.namespaces | toYaml | nindent 8 }}
      resources:
        {{- .Values.config.exclusions.resources | toYaml | nindent 8 }}
      selectors:
        {{- .Values.config.exclusions.selectors | toYaml | nindent 8 }}
      gvrs:
        {{- .Values.config.exclusions.gvrs | toYaml | nindent 8 }}
      bundles:
        {{- .Values.config.exclusions.bundles | toYaml | nindent 8 }}
