apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    argo-zombies/ignore: "true"
spec:
  schedule: {{ .Values.schedule | quote }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Forbid" }}
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: {{ default 60 .Values.ttlSecondsAfterFinished }}
      backoffLimit: {{  default 3 .Values.backoffLimit }}
      template:
        metadata:
          annotations:
            argo-zombies/ignore: "true"
        spec:
          restartPolicy: {{ default "Never" .Values.restartPolicy }}
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "chart.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          volumes:
            - name: argo-zombies-config
              configMap:
                name: {{ include "chart.fullname" . }}
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              command:
                - /argo-zombies
                - detect
                - --config
                - /config/.argo-zombies.yaml
              volumeMounts:
                - name: argo-zombies-config
                  mountPath: /config
              env:
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretRef:
                      name: {{ .Values.config.dashboards.github.tokenSecretRef.name | default "argo-zombies-dashboard-tokens" }}
                      key: {{ .Values.config.dashboards.github.tokenSecretRef.key | default "GITHUB_TOKEN" }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
